# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: '#research'
    weight: 10
  - name: Software
    url: '#software'
    weight: 11
  - name: Publications
    url: '#publication'
    weight: 12
  - name: News
    url: '#news'
    weight: 20
  - name: Team
    url: '#people'
    weight: 30
  - name: Events
    url: '#event'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 60
  - name: GitHub
    icon: github
    icon_pack: fab
    url: 'https://github.com/jaspershen-lab'
    weight: 70
