# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: ntu2
  theme_night: ntu2
  font: ntu2
  font_size: M

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo research group theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: '143314205'
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    block: navbar
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_translations: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  block: minimal2
  copyright:
    notice: '© {year} Shen Lab @ [Stanford University](https://mathrice.fr)'
    license:
      enable: false
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  responses:
    positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new)'
    negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  syntax_highlighter:
    theme_light: dracula
    theme_dark: dracula
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/jaspershen-lab/jaspershen-lab'
    content_dir: content
    branch: main
    editable: true
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'disqus'
    disqus:
      shortname: 'blog-at8qrhng8b'
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: 'KZN4XT95B1'
      api_key: 'ffb4e7ce2faa874ed5f9d8a121f86c2a'
      index_name: 'jaspershen-lab'
      show_logo: true
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: true
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

params:
  social:
    - icon: github
      icon_pack: fab
      link: https://github.com/jaspershen-lab

